site_name: DSA Study Plan
theme:
    name: material
    features:
    # Search-box settings
      - search.suggest
      - search.highlight
      - search.tabs.link
    # Navigation settings
      - navigation.instant
      - navigation.expand
      - navigation.path
    # Code-block copy button
      - content.code.copy

    palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
  
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    font:
      code: Roboto Mono

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Learn the basics:
    - Things to Know in C++ or any language:
      - C++ Input & Output: cpp_Input_and_Output.md
      - C++ Data Types: cpp_data_types.md
      - C++ Conditional Statements: cpp_conditional_statements.md