name: ci 
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # needs: spelling
    steps:
    - run: /usr/bin/python3 -m pip install --upgrade pip
    - run: /usr/bin/python3 -m pip install --upgrade setuptools
    - run: /usr/bin/python3 -m pip install --upgrade mkdocs
    - run: /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin
    - name: Check out main branch
      uses: actions/checkout@v2
      with:
        ref: main
    - run: git fetch -p
    - run: /usr/bin/python3 -m mkdocs gh-deploy -f web/mkdocs.yml -b website
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
